import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminPortalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header> 
        <h1>SMAC admin portal</h1>
      </header>
      
      <main>
        {children}
      </main>
    </>
  );
}
